/**
 * robots.txt body, as a pure function of the site URL.
 *
 * This used to be `static/robots.txt`, a flat file. That could not satisfy FND-07 ("SITE_URL
 * must come from PUBLIC_SITE_URL — never hardcoded"): a static file cannot interpolate anything,
 * so its `Sitemap:` line was pinned to `https://trinity-breath-healing.vercel.app/sitemap.xml`
 * and stayed pinned while the real domain moved. A crawler that honours the directive literally
 * — rather than guessing — would have gone looking for the sitemap on a stale preview alias.
 * `sitemap.xml` was already a generated route for exactly this reason; robots.txt now matches.
 *
 * Kept as a function rather than inlined into the route so the unit tests can assert the
 * ordering rules against the real text without a build or a populated environment.
 *
 * ORDER IS LOAD-BEARING. Named bot `Allow` blocks MUST precede `User-agent: *`. Several crawlers
 * apply the first matching group only, so a wildcard block placed first would shadow every named
 * one. `scripts/check-robots.sh` enforces this in CI and the unit tests assert it here.
 */
export function buildRobotsTxt(siteUrl: string): string {
	return `# robots.txt — Trinity Breath & Healing
# Generated by src/routes/robots.txt/+server.ts — do not add a static/robots.txt,
# it would shadow this route and re-introduce a hardcoded domain.
# Order is critical: named bot Allow blocks MUST precede User-agent: *
# scripts/check-robots.sh enforces this order in CI.

# ─── Search / RAG crawlers ────────────────────────────────────────────────────
User-agent: OAI-SearchBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Perplexity-User
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Claude-User
Allow: /

# ─── Training crawlers ────────────────────────────────────────────────────────
# DECISION: training crawlers (Google-Extended, Applebot-Extended) ALLOWED per CONTEXT.md (2026-06-15).
# Rationale: wellness content has low IP risk + high long-term citation surface in Gemini
# + Apple Intelligence baseline knowledge. Change requires architectural discussion.

User-agent: Google-Extended
Allow: /

User-agent: Applebot-Extended
Allow: /

# ─── Wildcard fallback ────────────────────────────────────────────────────────
User-agent: *
Allow: /
Disallow: /api/

Sitemap: ${siteUrl}/sitemap.xml
`;
}
